[package]
name = "envset"
version = "0.1.0"
edition = "2021"

[dependencies]
atty = "0.2"
clap = { version = "4.3", features = ["derive"] }
colored = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
